### PR TITLE
Data analytics

### PR DESCRIPTION
**Pull request by Purva-Raut**

### CODE REVIEW

**Comment by Stephen-Cole267** [comment]
Hi Purva, this is extremely good! Good visualisations with clear explanations of each process. I especially liked how you discovered that absolute values would be hard to interpret in terms of the business context so you converted them to rates which makes will make a lot more sense to the stakeholder. In Summary:

Things done well

- Clear outline of processes and findings
- Relevant to business objective throughout
- Clear explanation to the attributes related to employees attrition
- Used the in_time.csv and out_time.csv to create hrs and attendance
- Kept pptx to bullet points

To Improve

- Use a variety of charts to creatively portray the data, for example you could use line charts for the numerial data or the rates of columns with a lot of levels (PercentSalaryHike or YearsSinceLastPromotion). This will help keep the audience engaged and easily distinguish between the charts.
- Convert the ordinal columns to their original values using the data dictionary.
- Keep to 1 conclusion page could rename your Recommendation Summary to conclusion and change the others.
- This is extremely small but the beginning page has the wrong name of the company, should be JWC. This is minute but is important to clients, especially when it comes to their branding.
- Should have an ending slide that opens the audience up for questions.

Conclusion:
Overall, I'm very happy with the report and can clearly see which areas of the company that I need to focus on. Everything is done is a easily readible format and conveyed in a non-technical fashion. I would suggest using more types of charts like line charts and pie charts. Line charts would be good for seeing if there is an inter-relationship between the recommended columns, i.e. DistanceFromHome and MonthlyIncome.

**Comment by Purva-Raut** [comment]
Hi Stephen, thank you for the detailed review of the project. 

I will surely take your suggestion to include a variety of charts for a clear portrayal of the features in the dataset and provide original values to the chart because it is more easily readable than providing a key. 
I have noted your point of seeing inter-relationship between the columns which would have helped me to draw more interesting insights.  
Providing just one conclusion page surely makes more sense and gives more impact. 
I will include the 'any questions' slide at the end of the presentation henceforth. 
I am extremely sorry that I have included the incorrect name of the company and this is crucial since attention to detail is a must for data analysts. I will be more careful and proofread my reports henceforth.

Thank you for providing a detailed review of my project report and this will definitely help me to shape up my analysing and presentation skills.

**Review by Stephen-Cole267 — APPROVED** [review]
Approved as not enough time to make suggested changes due to current project with Xander

**Comment by alexnaylor1999** [comment]
Hi Purva,

Firstly, thanks for submitting the project! This is some fantastic work. I echo what Steve has said but here are some additional pointers and comments:

- What made you choose the median value for null imputation for NumCompaniesWorked and TotalWorkingYears?
- Really good visuals for attribution against features. On the whole, they were clear and provided an insight into what could be contributing to attrition. 
- Very interesting overworked insight. Good work!
- Clear presentation - huge plus.

Let me know if you have any further questions or comments :)

**Review by alexnaylor1999 — APPROVED** [review]

**Comment by Purva-Raut** [comment]
Hi Alex,

Thank you for your valuable review.

To answer your question:
- 'What made you choose the median value for null imputation for NumCompaniesWorked and TotalWorkingYears'?
- 'NumCompaniesWorked' and 'TotalWorkingYears' have discrete values e.g. 1,5,10. The mean of NumCompaniesWorked is 2.69, Median of NumCompaniesWorked is 2. Similarly, the Mean of TotalWorkingYears is 11.27, Median of TotalWorkingYears is 10. The mean values are continuous data and medians are discrete. Hence, I thought of filling the null values of  NumCompaniesWorked and TotalWorkingYears with the median values. 
This was my logic. Kindly, let me know if it is correct.

I have noted a mistake in my notebook where I mention NumCompaniesWorked and TotalWorkingYears are continuous numeric columns where they clearly are discrete values.
I will rework the suggested changes.

Once again thank you for your review.

**Pull request merged**
