### PR TITLE
Data science

### PR DESCRIPTION
**Pull request by aalogan**

### CODE REVIEW

**Comment by alexnaylor1999** [comment]
Hi @aalogan, thanks for submitting your notebook for a review - this is exactly what we want to see from associates! This is an excellent start and you're definitely heading in the right direction. 

Here are some suggestions/feedback:

- Try setting your column and row display options at the start of your notebook - maybe just after importing all the packages you need. I noticed that for output cell 7 you couldn't see all of the feature results.
- Excellent feature engineering for in_time/out_time - it's fantastic to see it come out as an important feature for some of the models. Could you complete analysis of employees who took a sustained period off i.e. over a week? Could this be down to holidays or employees being ill? Granted the data is limited but in a client situation, if ill should a model penalise employees who can't work? Just food for thought ...
- Curious about your thoughts on mean imputation for numeric nulls - what if the data is skewed?
- Should certain features be kept in the model for ethical reasons i.e. age? Should we be concerned about discrimination?
- Small data set so not too much of an issue, but worth considering feature selection in the future.
- Target class is imbalanced - have you thought about oversampling or undersampling to improve performance?
- Could tuning other parameters in hyperparameter grid for logistic regression or tuning parameters in XGBoost improve performance? 

I really liked your use of visuals, especially the KDEs for the features against the target variable. Also, it's great that you used XGBoost, Logistic Regression and SHAP.

Let me know your thoughts on the points above - maybe you could try the report as another task if you have time :) 

Cheers!

**Comment by Stephen-Cole267** [comment]
Really impressed! I especially liked how you connected pgAdmin4 to Python! Overall I'm happy with the resulting model and clearly shows the important features. In summary:

Things I liked:
- Good data exploration
- Completed most stages of the modelling lifecycle
- Clear and concise coding (easy to understand and follow)
- Very good visuals
- Worked out a way to use the in-time and out-time csvs
- Tried logistic regression and XGBoost models
- Used good visuals to represent the model performance

To Improve:
- Used the data dictionary to convert the columns into categoricals i.e. ```Education``` and ```EnvironmentSatisfaction```. This is because the model will treat them like numericals which is good in modelling context, but in business context it is not accurate. It will also give more insight into the levels of the categories, for example, someone with an outstanding ```PerformanceRating```. would be a lot more indicative or being a negative class for attrition than excellent. 
- I noticed that you changed all the columns to categoricals on the back end of your notebook and was wondering what your reasoning behind that was? 
- It would be good to reduce the number of features in the model as well, as at the moment all of them are included. Although it is more likely to give better performance to the model, it will not be as reliable as it means there are more dependencies in the model which increases the risk of not being able to run properly if there is something wrong within the data pipeline, or if any calculations within the database changes.
- Formatting could also be slightly improved by keeping all imports in one place. This helps keep the notebook clean and anyone can clearly see all packages used without having to filter through the entire notebook.
- Could also split this notebook into several notebooks but in different stages. For example, one notebook for data gathering or preprocessing, another for modelling, and a final one for evaluation.
- Can use Gain and Lift plots to evaluate the performance of logistic models.

**Comment by alexnaylor1999** [comment]
Nice @Stephen-Cole267 - didn't even think about the Gain and Lift charts!

**Comment by aalogan** [comment]
Stephen and Alex,

Thanks for the comprehensive feedback - much appreciated.

Good call re column display - next time I'll add it at the start of the
notebook (also for all imports at the beginning - Stephen)
Stephen - breaking up into shorter notebooks certainly makes sense!
Stephen - initially I left the ordinally ranked as numerical as there was a
possibility that the degree of eg satisfaction could be useful (more
satisfied could increase the likelihood of something). It turned out that
it wasn't, so they were converted to categorical and the model results
improved.
Interesting point re illness as a potential factor - I hadn't thought of
that and would need to mull over it as to how to extract from the given
data reliably.
There was a thought process re mean as fill (as opposed to median or other
methods) - in this case, the data did not seem particularly skewed and so
the mean seemed appropriate.
Makes sense re age - certainly something I would want to explore further
with a live client/end-user. It could also be interesting to explore
further the correlation between age and other features.
Some (non-useful) features were removed - I kept in the ones that I thought
would be useful. Stephen - re production environment, wouldn't it make more
sense to use as many useful features to begin with and monitor the
performance in production, rather than arbitrarily removing features
up-front?
Re imbalanced target class - if the xgboost results hadn't been as good, I
would have looked at other ways to improve the results - including sampling
techniques.
I didn't investigate further logistic regression tuning once the xgboost
results arrived - but you're right, there are other tunable parameters that
might have helped. Re xgboost - my first time using it, so need to spend
some more time exploring the tuning options!

Once again - thanks for taking the time to take a look and letting me know
your thoughts.

Andrew

**Comment by alexnaylor1999** [comment]
@aalogan Thanks for taking the time to respond. XGBoost is common practice in the industry for problems like this. For example, the only models used in recent times within DS team at VM O2 were XGBoost. The python package documentation is pretty comprehensive and provides a good explanation of the algorithm, so I would recommend looking there to familiarise yourself with it further if you already haven't.  In the future, I would recommend starting with XGBoost and then looking into other options if the model performance isn't great. 

If you're going to look into feature correlation, Steve and I have used Variance Inflation Factors in the past. We also have looked at the variance of features and removed features with extremely low variance before any modelling - they will not bring anything useful to the model.

**Comment by Stephen-Cole267** [comment]
> Stephen - re production environment, wouldn't it make more sense to use as many useful features to begin with and monitor the performance in production, rather than arbitrarily removing features up-front?

Theoretically yes, however its not very practical to use every feature as sometimes you can have datasets which are 500+ columns long before One Hot Encoding. Therefore, it is best to recursively remove features while assessing its performance and choosing the number of features which still performs well. This reduces the amount of reliance of a complete dataset and makes the model more robust. I hope this makes sense?

**Comment by Stephen-Cole267** [comment]
Really happy with this notebook, happy to merge. @alexnaylor1999 thoughts?

**Review by Stephen-Cole267 — APPROVED** [review]

**Comment by alexnaylor1999** [comment]
All good with me @Stephen-Cole267. Great work @aalogan !

**Review by alexnaylor1999 — APPROVED** [review]

**Pull request merged**
